baseURL = "https://kishansagathiya.github.io/"
languageCode = "en-us"
title = "Kishan Sagathiya"
theme = "hugo-theme-codex"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "PullRecruit"
    weight = 3
    identifier = "PullRecruit"
    url = "https://pullrecruit.masterinai.com/score/kishansagathiya"
  [[menu.main]]
    name = "Master in AI"
    weight = 4
    identifier = "masterinai"
    url = "https://masterinai.com/"
  [[menu.main]]
    name = "Talks"
    weight = 5
    identifier = "talks"
    url = "/talks/"
  [[menu.main]]
    name = "Old Blog"
    weight = 6
    identifier = "oldblog"
    url = "https://medium.com/@kishansagathiya"
  [[menu.main]]
    name = "Posts"
    weight = 7
    identifier = "posts"
    url = "/posts/"

[social]
github="https://github.com/kishansagathiya"
linkedin="https://www.linkedin.com/in/kishansagathiya/"

[params]
headTitle = "Kishan Sagathiya"
subtitle = "Software Engineer insterested in Distributed Systems, P2P, Privacy technology and AI"
favicon = "/imgs/favicon.png"
github = "https://github.com/kishansagathiya"
linkedin = "https://www.linkedin.com/in/kishansagathiya/"
iconOrder = ["LinkedIn", "GitHub"]

[[params.socials]]
name = "About Me"
link = "/about"
[[params.socials]]
name = "Github"
link = "https://github.com/kishansagathiya"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/kishansagathiya/"

[author]
    name = "Kishan Sagathiya"
    github = "kishansagathiya"
    linkedin = "kishansagathiya"

